### PR TITLE
Update player-warps.md

### PR DESCRIPTION
**Pull request by ghost**
Added more commands, the formatting for setting a pw description and rank 2 requirement

### CODE REVIEW

**Review by lukemango — CHANGES_REQUESTED** [review]
Appreciate the PR - however please be consistent with how you refer to a player warp in your command descriptions and can you fix the left-over gramatical errors:

All command descriptions: please remove the full stop/periods as they are not sentences
Line 21: Remove the space after Set/ so remove
Line 22: Does not require a period after icon, simply use '-' instead
Line 24: Player warp is referred to as 'PW', not 'Player Warp'
Line 27: Player warp is referred to as 'Playerwarp', not 'Player Warp'
Line 28: 'Remove' should not be capitalised, player warp is referred to as 'PW', not 'Player Warp'

**Review by ghost — COMMENTED** [review]
Repaired Items Requested
Reworded Sentences
IM SO LOST IN THIS GUI :-;

**Comment by lukemango** [comment]
```* /pw desc set/remove <warp> <description> - Set/remove descriptions (uses legacy '&' formatting)
* /pw icon set/remove <warp> - Set/remove icon - will use the item you are holding in your hand
* /pw rename <warp> <newname> - Rename your warp (cost: £2500)
* /pw ban set/remove <warp> <player> - Ban/remove a banned player from your Player Warp
* /pw rate <warp> <1-5> - Give a Player Warp a rating between 1 to 5 stars
* /pw reset <warp> - Reset a Player Warp location
* /pw lock <warp> - Locks/unlocks Player Warp access
* /pw password <set/remove> <warp> <password> - Set/remove a password for accessing a Player Warp

**Review by ghost — COMMENTED** [review]
added slashes back in :)

**Review by lukemango — APPROVED** [review]

**Pull request merged**
